<?php
//
// utilizado no shortcode do Wordpress para o mapa de assentamentos humanos
// na pagina população
// http://desenv.saude.df.gov.br/populacao/
//
$corpoconfig = array(
    "legenda" => true,
    "tipoInterface" => "OSM",
    "debug" => ""
);
include ("corposingle.php");
?>
<style>
#i3GEOcopyright {
	display: none;
}
#i3GEOzoomInOut {
    z-index: 10;
}
</style>
<script>
<?php include ("corpo_script.php"); ?>
parametrosMapa.layers = {
    add : [
        "unidades","ridedf2016",
        "ghspopgpw42015glober2015a54009250v10",
        "ghspopgpw42000glober2015a54009250v10",
        "ghspopgpw41990glober2015a54009250v10",
        "ghspopgpw41975glober2015a54009250v10",
        "regioesdesaude","regioesdesaudenomes"],
    on : [],
    off : ["unidades","ridedf2016",
        "ghspopgpw42000glober2015a54009250v10",
        "ghspopgpw41990glober2015a54009250v10",
        "ghspopgpw41975glober2015a54009250v10",
        "regioesdesaude","regioesdesaudenomes"]
};
//Funcao que sera executada apos a inicializacao do mapa
config.afterStart = function() {
    new ol.control.Zoom({
        target: $i("i3GEOzoomInOut")
    }).setMap(i3geoOL);
};
i3GEO.init(parametrosMapa, config);
</script>
<div style="position: absolute; top: 0px; margin: auto; width: 100%; height: 40px; background-color: #fff9;">
    <div class="togglebutton text-left" style="display: inline;">
        <label style="color: black;">
            <input  type="checkbox" value="ghspopgpw41975glober2015a54009250v10" name="ghspopgpw41975glober2015a54009250v10"
                onclick="i3GEO.Interface.ligaDesliga(this);i3GEO.eventos.executaEventos(i3GEO.eventos.ATUALIZAARVORECAMADAS);">
            <span class="toggle" style="margin-right: 8px;"></span>1975
        </label>
    </div>
    <div class="togglebutton text-left" style="display: inline;">
        <label style="color: black;">
            <input  type="checkbox" value="ghspopgpw41990glober2015a54009250v10" name="ghspopgpw41990glober2015a54009250v10"
                onclick="i3GEO.Interface.ligaDesliga(this);i3GEO.eventos.executaEventos(i3GEO.eventos.ATUALIZAARVORECAMADAS);">
            <span class="toggle" style="margin-right: 8px;"></span>1990
        </label>
    </div>
    <div class="togglebutton text-left" style="display: inline;">
        <label style="color: black;">
            <input  type="checkbox" value="ghspopgpw42000glober2015a54009250v10" name="ghspopgpw42000glober2015a54009250v10"
                onclick="i3GEO.Interface.ligaDesliga(this);i3GEO.eventos.executaEventos(i3GEO.eventos.ATUALIZAARVORECAMADAS);">
            <span class="toggle" style="margin-right: 8px;"></span>2000
        </label>
    </div>
    <div class="togglebutton text-left" style="display: inline;">
        <label style="color: black;">
            <input checked type="checkbox" value="ghspopgpw42015glober2015a54009250v10" name="ghspopgpw42015glober2015a54009250v10"
                onclick="i3GEO.Interface.ligaDesliga(this);i3GEO.eventos.executaEventos(i3GEO.eventos.ATUALIZAARVORECAMADAS);">
            <span class="toggle" style="margin-right: 8px;"></span>2015
        </label>
    </div>
    <div style="display: inline;">
        <a href=https://ghsl.jrc.ec.europa.eu/data.php target=_blank>Fonte: GHSL</a>
    </div>
</div>
<img style="position: absolute;top: 100px;left: 11px;" src="https://mapas.saude.df.gov.br/i3geo/ogc.php?legenda=sim&legenda_keyspacingy=&legenda_font=arial&SRS=EPSG:4326&WIDTH=155&HEIGHT=90&BBOX=-48.2851,-16,-47.30,-15.5&FORMAT=svg&service=wms&version=1.1.0&request=getlegendgraphic&layers=ghspopgpw42015glober2015a54009250v10"/>
</body>
</html>
